//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsmanShop.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverMaterialSupplier
    {
        public int Id { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DeliverDate { get; set; }
    
        public virtual MaterialOnWarehouse MaterialOnWarehouse { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
